version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "hw15"
      POSTGRES_USER: "hw15"
      POSTGRES_PASSWORD: "hw15"
    ports:
      - "6432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"
