## see https://github.com/uber-go/zap/blob/master/config.go
logger:
  level: info
  encoding: console
  encoderConfig:
    timeKey:        ""
    levelKey:       "L"
    nameKey:        "N"
    callerKey:      "C"
    messageKey:     "M"
    stacktraceKey:  "S"