logger:
  ## see https://github.com/uber-go/zap/blob/master/config.go
  level: debug
  encoding: console
  development: false
  encoderConfig:
    timeKey:        ""
    levelKey:       "L"
    nameKey:        "N"
    callerKey:      "C"
    messageKey:     "M"
    stacktraceKey:  ""
httpServer:
  host: "0.0.0.0"
  port: 5000
  readTimeout: 15s
  writeTimeout: 60s
  idleTimeout: 5s
grpcServer:
  host: "0.0.0.0"
  port: 5001
  enforcementPolicy:
    minTime: 5s
    permitWithoutStream: true
  serverParameters:
    maxConnectionIdle: 15s
    maxConnectionAge: 30s
    maxConnectionAgeGrace: 5s
    time: 5s
    timeout: 1s
storage:
  usePostgres: true
  postgresConnection: "postgres://hw12:hw12@localhost/hw12?sslmode=disable"
shutdownTimeout: 6s
